name: depoly on push
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my_image:latest
        
    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.HOST_SERVER }}
        username: ${{ secrets.HOST_USER_NAME }}
        key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          mkdir -p /home/ubuntu/app
          cd /home/ubuntu/app
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker-compose down
          docker-compose pull
          docker-compose up -d